### ISSUE TITLE
About NYUv2 dataset format?

### ISSUE THREAD

**Issue by rxqy** [dontLoveBugs/FCRN_pytorch#2]
Hi, good job here. 
I tried to run your code on NYUv2 dataset. From their website, the dataset is in '.mat' format.  So how do I convert the dataset to fit in your implementation? Thank you very much!

**Comment by dontLoveBugs** [comment]
Hi, you can find the convert script from [there](https://github.com/dontLoveBugs/DORN_pytorch/blob/master/tool/create_nyu_h5.py)

**Comment by rxqy** [comment]
Much obliged!
